spring.application.name=notificacao-service
spring.datasource.url=jdbc:postgresql://localhost:5432/bank-api
spring.datasource.username=postgres
spring.datasource.password=1010
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.instance.instance-id=${spring.application.name}:${random.int}
eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=rbrodrigo3@gmail.com
spring.mail.password=nysw wdbb vjfa kzqh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=0