spring.application.name=banking-api
spring.datasource.url=jdbc:postgresql://localhost:5432/bank-api
spring.datasource.username=postgres
spring.datasource.password=123
server.forward-headers-strategy=framework

eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka
server.port=0
eureka.instance.prefer-ip-address=true
logging.level.org.springframework.security=DEBUG
eureka.instance.instance-id=${spring.application.name}:${random.int}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
api.security.token.secret=segredinho-api
logging.level.org.springframework.security=DEBUG